bindswitch --reload --locked lid:on output eDP-1 disable
bindswitch --reload --locked lid:off output eDP-1 enable

# Alsa Audio controls
# bindsym XF86AudioRaiseVolume exec amixer -D hw:0 set Master 3dB+
# bindsym XF86AudioLowerVolume exec amixer -D hw:0 set Master 3dB-
# bindsym XF86AudioMute exec amixer -D hw:0 set Master 0%, mute

# bindsym XF86MonBrightnessDown exec brightnessctl set 5%-
# bindsym XF86MonBrightnessUp exec brightnessctl set +5%

output eDP-1 pos 0 0 res 1366x768

output HDMI-A-1 pos 0 0 res 3840x2160
output HDMI-A-1 scale 2
