background #121212
foreground #bebebe
cursor #c69957
selection_background #2a2a2a
color0 #363434
color8 #535050
color1 #D35F5F
color9 #bcab2b
color2 #FFC107
color10 #FFC107
color3 #986fa3
color11 #0aa4b9
color4 #e68e0d
color12 #f59e0b
color5 #D35F5F
color13 #de7c6d
color6 #bebebe
color14 #eaeaea
color7 #bebebe
color15 #bebebe
selection_foreground #262628
