[QuickNoteDialog]
windowsize=(478, 718)
lastnotebook=file:///home/b08x/Notebooks/Current
open_page=True
new_page=True

[Namespaces]
file:///home/b08x/Notes=Home:notes
file:///home/b08x/Notebooks/Current=Home:notes

