#!/usr/bin/env bash
# =============================================================================
# YADM Master Bootstrap Orchestrator
# =============================================================================

# --- Error Handling ---
ctrl_c() {
  echo "** End."
  sleep 1
}
trap ctrl_c INT SIGINT SIGTERM ERR EXIT

# --- Colors ---
ALL_OFF="\e[1;0m"
BBOLD="\e[1;1m"
BLUE="${BBOLD}\e[1;34m"
GREEN="${BBOLD}\e[1;32m"
RED="${BBOLD}\e[1;31m"
YELLOW="${BBOLD}\e[1;33m"
export GUM_INPUT_WIDTH=0

DISTRO=$(lsb_release -si)

# --- Display Function ---
say() {
  echo -e "${2}${1}${ALL_OFF}"
  sleep 1
}


# --- Wipe Screen Function ---
wipe() {
  tput -S <<!
clear
cup 1
!
}

# --- Display Welcome Message ---
display_welcome_message() {
  wipe
  # Now we can use gum for the rest of the script
  gum style --border normal --margin "1" --padding "1 2" --border-foreground 212 "This bootstrap script is about to configure some stuff. Welcome to $(gum style --foreground 212 'synflow')."
  sleep 1
}


# --- Get Environment Variables ---
get_environment_variables() {
  say "Enter additional environment variables (press Enter with empty input to finish): \n" $BLUE

  declare -A env_vars
  declare var_name=""

  while true; do
    var_name=$(gum input --width=0 --prompt "Variable name (or Enter to finish): ")

    if [[ -z "${var_name}" ]]; then
      break
    else
      var_value=$(gum input --prompt "Value for ${var_name}: ")
      env_vars["${var_name}"]="${var_value}"
    fi
  done

  echo "$env_vars"
}


# --- Main Script ---
# Set up variables
declare -rx USER_HOME="${HOME}"
declare -rx CONFIG_DIR="${USER_HOME}/.config"

echo $DISTRO


display_welcome_message

sleep 1

sudo usermod -s /usr/bin/zsh $USER
