Threshold = 95
DisplayMonitorSources = false
EnableUpdates = true
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.usb-Dictaphone_Corporation_PowerMicII-NS-00.mono-fallback"
LastUsedOutput = ""
