#!/bin/bash

scp_host=$SCP_HOST
scp_path_img=/home/b08x/Library/Images/Screenshots
scp_path_vid=/home/b08x/Library/Videos/Screencasts
scp_path_paste=/home/b08x/Library/Images/Pastes
#http_img=https://YOUR_DOMAIN/path/to/images
#http_vid=https://YOUR_DOMAIN/path/to/videos
#http_paste=https://YOUR_DOMAIN/path/to/pastes
