#!/home/b08x/.vibe/.venv/bin/python3
"""
Agent Creator Workflow - High Performance Implementation
----------------------------------------------------------------------
Orchestrates agent creation using structured data and minimal LLM chatter.
Uses tomli_w for safe generation and supports SFL/Steve-mode delegation.
"""

import json
import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Any

import tomli
import tomli_w
import yaml

# --- Configuration ---
VIBE_ROOT = Path.home() / ".vibe"
SKILL_DIR = VIBE_ROOT / "skills" / "agent-creator"
AGENTS_DIR = VIBE_ROOT / "agents"
PROMPTS_DIR = VIBE_ROOT / "prompts"
TEMP_DIR = VIBE_ROOT / "temp" / "agent-creator"

# Ensure directories exist
for d in [AGENTS_DIR, PROMPTS_DIR, TEMP_DIR]:
    d.mkdir(parents=True, exist_ok=True)

class AgentCreationError(Exception):
    """Base exception for agent creation errors."""
    pass

def log(message: str, level: str = "INFO") -> None:
    """Log a message to stdout."""
    print(f"[{level}] {message}")

def load_yaml(filepath: Path) -> Dict:
    with open(filepath, "r") as f:
        return yaml.safe_load(f)

def load_toml(filepath: Path) -> Dict:
    with open(filepath, "rb") as f:
        return tomli.load(f)

def validate_agent_id(agent_id: str) -> str:
    if not re.match(r"^[a-z0-9_-]+$", agent_id):
        raise AgentCreationError(f"Invalid agent ID: {agent_id}")
    return agent_id

def ask_task_delegation(agent: str, task_desc: str) -> str:
    """
    In Mistral Vibe, the agent would see this print and call the task tool.
    We output a specific marker for the orchestrator to pick up.
    """
    print(f"\n[AGENT_TASK_REQUEST]")
    print(json.dumps({"agent": agent, "task": task_desc}))
    print("[END_TASK_REQUEST]\n")
    
    # In a script-driven flow, we'd wait for input or the orchestrator to resume.
    # Since we can't pause easily here, we instruct the user/agent.
    print(f"Waiting for {agent} output...")
    # This is where the script would ideally stop and wait, but in this env
    # we might need to rely on the agent to feed the result back.
    return input("Paste subagent output here: ").strip()

def generate_agent_files(config: Dict) -> List[Path]:
    """Generates TOML and Markdown files using tomli_w."""
    agent_id = validate_agent_id(config["agent_id"])
    
    # 1. TOML Generation
    agent_data = {
        "id": agent_id,
        "display_name": config["agent_name"],
        "description": config.get("description", ""),
        "agent_type": config.get("agent_type", "agent"),
        "safety": config.get("safety_level", "neutral"),
        "auto_approve": config.get("auto_approve", False),
        "system_prompt_id": config.get("system_prompt_id", agent_id),
        "user_invocable": config.get("user_invocable", True),
        "enabled_tools": config.get("enabled_tools", ["read_file", "grep"]),
        "disabled_tools": config.get("disabled_tools", ["bash"]),
    }
    
    # Add tool configs
    agent_data["tools"] = {}
    for tool in agent_data["enabled_tools"]:
        agent_data["tools"][tool] = {"permission": "always" if tool in ["read_file", "grep"] else "ask"}
    
    # Specialized tool configs if provided
    if config.get("bash_allowlist"):
        agent_data["tools"]["bash"] = {
            "permission": "ask",
            "allowlist": config["bash_allowlist"]
        }
        
    agent_data["session_logging"] = {
        "enabled": True,
        "session_prefix": agent_id
    }
    
    toml_path = AGENTS_DIR / f"{agent_id}.toml"
    with open(toml_path, "wb") as f:
        tomli_w.dump(agent_data, f)
        
    # 2. Prompt Generation (Markdown)
    prompt_path = PROMPTS_DIR / f"{agent_data['system_prompt_id']}.md"
    
    # If we have an SFL prompt from a subagent, use it.
    prompt_text = config.get("system_prompt_text")
    if not prompt_text:
        prompt_text = f"# {agent_data['display_name']} System Prompt\n\nGenerated by agent-creator."
        
    with open(prompt_path, "w") as f:
        f.write(prompt_text)
        
    return [toml_path, prompt_path]

def main():
    print("🚀 Mistral Vibe Agent Creator Engine")
    print("------------------------------------")
    
    # Phase 0: Basic Info
    agent_id = input("Agent ID (slug): ").strip().lower()
    agent_name = input("Agent Display Name: ").strip()
    description = input("Description: ").strip()
    
    # Phase 1: Skills & Tools
    skills = input("Existing skills (comma separated): ").strip()
    tools_raw = input("Tools to enable (e.g. read_file,grep,bash): ").strip()
    enabled_tools = [t.strip() for t in tools_raw.split(",") if t.strip()]
    
    # Phase 2: SFL Delegation (Optional)
    print("\n[DECISION] Delegate prompt engineering to SFL subagent? (y/N)")
    use_sfl = input("> ").lower().startswith('y')
    
    prompt_text = None
    if use_sfl:
        task_desc = f"Generate a high-performance system prompt for '{agent_name}'. Purpose: {description}. Skills: {skills}."
        prompt_text = ask_task_delegation("sfl-prompt-engineer", task_desc)
        if "[SUBAGENT_OUTPUT]" in prompt_text:
            prompt_text = prompt_text.split("[SUBAGENT_OUTPUT]")[1].strip()

    # Final Generation
    config = {
        "agent_id": agent_id,
        "agent_name": agent_name,
        "description": description,
        "enabled_tools": enabled_tools,
        "system_prompt_text": prompt_text,
        "enabled_skills": skills.split(",") if skills else []
    }
    
    try:
        files = generate_agent_files(config)
        print("\n✅ Success! Created:")
        for f in files:
            print(f"   - {f}")
    except Exception as e:
        print(f"\n❌ Error: {e}")

if __name__ == "__main__":
    main()
