# frozen_string_literal: true

source 'https://rubygems.org'

gem 'front_matter_parser', '~> 1.0'
gem 'gli', '~> 2.21'
gem 'pry'
gem 'tty-config', '~> 0.5'
gem 'tty-editor', '~> 0.7'
gem 'tty-prompt', '~> 0.23'

group :development do
  # Development-only gems
  gem 'lint_roller'
  gem 'listen', require: false
  gem 'parallel'
  gem 'rainbow'
  gem 'regexp_parser'
  gem 'rubocop', require: false
  gem 'rubocop-packaging'
  gem 'rubocop-performance'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'rubocop-shopify'
  gem 'rubocop-thread_safety'
  gem 'ruby-lsp'
  gem 'ruby-progressbar'
  gem 'solargraph'
  gem 'unicode-display_width'
  gem 'webrick'
end

gem 'table_tennis', '~> 0.0.6'

gem 'ruby_llm', '~> 1.3'

gem 'nano-bots', '~> 3.4'

gem "google_custom_search_api", "~> 2.0"
